name: Build OpenWrt
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Installation depends
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
    - name: Clone source code
      run: |
        git clone https://github.com/liuyi0904lyx/action.git openwrtmtt
        git clone -b openwrt-21.02 https://git.openwrt.org/openwrt/openwrt.git
        cd openwrtmt
        echo "src-git mtk_openwrt_feed https://git01.mediatek.com/openwrt/feeds/mtk-openwrt-feeds" >>
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cd $GITHUB_WORKSPACE/openwrtmtt
        cp .config $GITHUB_WORKSPACE/openwrtmt
        cp -af ./feeds/mtk_openwrt_feed/21.02/files/* .
cp -af ./feeds/mtk_openwrt_feed/tools .
for file in $(find ./feeds/mtk_openwrt_feed/21.02/patches-base -name "*.patch" | sort); do patch -f -p1 -i ${file}; done
for file in $(find ./feeds/mtk_openwrt_feed/21.02/patches-feeds -name "*.patch" | sort); do patch -f -p1 -i ${file}; done

    - name: Download package
      run: |
        cd openwrtmt && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build
      run: |
        cd openwrtmt
        make -j$(nproc)
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrtmt/bin
